interface TombstoneV1 {
  readableId: string,
  version: string,
  uid: string,
  os: string,
  time: number,
  backtraceRefs: string[],
  memoryRefs: string[],
  backtraceRefIds: string[],
  memoryRefIds: string[],
  signalInfo: string,
  log: string | Buffer,
};

interface TombstoneV2 {
  v: 2,
  readableId: string,
  time: number,
  version: string,
  uid: string,
  os: string,
  prevScene: string,
  nextScene: string,
  sceneTime: string,
  rsp: string,
  rlr: string,
  rpc: string,
  sig: string,
  faddr: string,
  backtraceRefs: string[],
  memoryRefs: string[],
  backtraceRefIds: string[],
  memoryRefIds: string[],
  logcat: string,
  backtrace: string | Buffer,
};
